name: CI

on:
  pull_request:
    branches: [ "master", "test" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Install WiX Toolset
      run: dotnet tool install --global wix

    - name: Build CLI
      run: dotnet build Max\Max.csproj -c Release -p:Platform=x64

    - name: Build Service
      run: dotnet build MaxBackup.ServiceApp\MaxBackup.ServiceApp.csproj -c Release -p:Platform=x64

    - name: Run tests
      run: dotnet test Max.IntegrationTests\Max.IntegrationTests.csproj --configuration Release --logger "trx;LogFileName=test-results.trx"

    - name: Build installer
      run: dotnet build Max.Installer.Package\Max.Installer.Package.wixproj -c Release -p:Platform=x64
